name: Build and Test

# This will trigger the workflow on every push or pull request to the master or feature branches.
on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (or whichever version you're using)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # AdoptOpenJDK/Temurin
          java-version: '17'

      # Step 3: Cache Gradle dependencies to speed up build
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Build the project using Gradle
      - name: Build the project
        run: ./gradlew build --no-daemon

      # Step 5: Run unit tests (including Mockito tests)
      - name: Run tests
        run: ./gradlew test --no-daemon

      # Step 6: Archive test results for viewing in GitHub (optional)
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test
